config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # 前台
  # 只有顯示無其他功能, only, except皆可使用
  # 新增評論
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
    
    # 瀏覽所有餐廳的最新動態
    # "Verb" "Action Name", :on => ":member or :collection"
    get :feeds, :on => :collection
    # Top10人氣餐廳
    get :ranking, :on => :collection

    # 瀏覽個別餐廳的 Dashboard
    get :dashboard, :on => :member
    # 收藏餐廳
    post :favorite, :on => :member
    post :unfavorite, :on => :member
    # 按讚餐廳
    post :like, :on => :member
    post :unlike, :on => :member

  end
  
  # 個人資訊
  resources :users, only: [:index, :show, :edit, :update]

  # resources :restaurants, except: [:new, :create, :edit, :update, :destroy]
  resources :categories, only: :show
  root "restaurants#index"
  
  # 追蹤達人
  resources :followships, only: [:create, :destroy]

  # 後台
  # url path for admin 
  # 避免被猜出後台位置, 可修改名稱用path 替換 admin
  # namespace :admin , path: "nobody123know" do
  namespace :admin do
    resources :restaurants
    resources :categories 
    root "restaurants#index"
  end
end

app/views/shared/_favorite.html.erb
<% if restaurant.is_favorited?(current_user) %>
  <%= link_to 'Unfavorite', unfavorite_restaurant_path(restaurant), data: { disable_with: "Please wait..." }, method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to 'Favorite', favorite_restaurant_path(restaurant), data: { disable_with: "Please wait..." }, method: :post, class: "btn btn-primary" %>
<% end %>

app/views/shared/_follow.html.erb
<% if user != current_user %>
  <% if current_user.following?(user) %>
    <!-- 會用 DELETE 動作導向 http://localhost:3000/followships/{user.id} -->
    <%= link_to 'Unfollow', followship_path(user), method: :delete, class: "btn btn-link" %>
  <% else %>
    <!-- 會用 POST 動作導向 http://localhost:3000/followships?following_id={user.id} -->
    <%= link_to 'Follow', followships_path(following_id: user), method: :post, class: "btn btn-link" %>
  <% end %>
<% end %>

app/views/shared/_like.html.erb
<% if restaurant.is_liked?(current_user) %>
  <%= link_to 'Unlike', unlike_restaurant_path(restaurant), data: { disable_with: "Please wait..." }, method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to 'Like', like_restaurant_path(restaurant), data: { disable_with: "Please wait..." }, method: :post, class: "btn btn-primary" %>
<% end %>

app/views/shared/_restaurant_list.html.erb
<!-- restaurants list，有多寫restaurant-item的class style -->
<% @restaurants.each do |restaurant| %>
  <div class="col-xs-12 col-sm-6 col-md-4">
    <div class="restaurant-item">
      <%= image_tag restaurant.image, class: "img-responsive center-block" if restaurant.image?%>
      <%= image_tag "http://via.placeholder.com/350x180", class: "img-responsive center-block img-rounded"  unless restaurant.image?%> 
      <div class="caption">
        <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
        <%= simple_format restaurant.category.name, class: "label label-default" %>
        <p class="description"><%= truncate(restaurant.description, length: 80) %></p>
        <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
        <%= render partial: "shared/like", locals: {restaurant: restaurant} %>
      </div>
    </div>
  </div>
<% end %>